##### Librerías

In [11]:
import pandas as pd
import numpy as np

## Dataset

In [24]:
# Lectura de dataset
df = pd.read_csv('weatherAUS_2026C2.csv')
df.head()

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,RainfallTomorrow
0,0,2008-12-01,Albury,13.6,22.5,0.6,NaN,NaN,W,45.0,...,23.8,1008.1,1007.2,8.0,NaN,16.8,20.8,No,No,0.0
1,1,2008-12-02,Albury,7.3,25.8,0.0,NaN,NaN,WNW,44.0,...,22.1,1011.1,1007.5,NaN,NaN,18.3,24.6,No,No,0.0
2,2,2008-12-03,Albury,13.2,26.2,0.0,NaN,NaN,WSW,46.0,...,31.5,1007.3,1009.4,NaN,2.0,21.2,23.4,No,No,0.0
3,3,2008-12-04,Albury,10.0,28.8,0.0,NaN,NaN,NE,23.0,...,18.5,1017.6,1012.4,NaN,NaN,17.4,26.3,No,No,1.0
4,4,2008-12-05,Albury,17.4,32.4,1.0,NaN,NaN,W,41.0,...,34.6,1010.9,1005.9,7.0,8.0,17.9,29.1,No,No,0.2

### Descripcion

In [13]:
df.shape

(145412, 25)

In [14]:
df.describe()

,Unnamed: 0,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainfallTomorrow
count,145412.000000,143928.000000,144159.000000,142152.000000,82658.000000,75616.000000,135159.000000,143645.000000,142351.000000,142759.000000,140907.000000,130351.000000,130388.000000,89542.000000,86076.000000,143646.000000,141805.000000,142153.000000
mean,72728.184393,12.196528,23.223064,2.361516,5.468616,7.611241,40.036668,14.067277,18.661899,68.861521,51.532206,1017.647237,1015.255080,4.447287,4.509770,16.991981,21.683360,2.361242
std,41990.722236,6.417956,7.135927,8.479338,4.193871,3.785612,13.648259,8.936768,8.865457,19.062866,20.844414,7.113833,7.044507,2.887161,2.720306,6.509191,6.953072,8.479084
min,0.000000,-9.700000,-5.100000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.300000,977.400000,0.000000,0.000000,-8.000000,-5.800000,0.000000
25%,36362.750000,7.600000,17.900000,0.000000,2.600000,4.800000,31.000000,7.000000,12.000000,57.000000,36.600000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,0.000000
50%,72727.500000,12.000000,22.600000,0.000000,4.800000,8.400000,38.000000,13.000000,18.000000,69.900000,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,0.000000
75%,109093.250000,16.900000,28.200000,0.800000,7.400000,10.600000,48.000000,19.000000,24.000000,83.100000,65.700000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,0.800000
max,145458.000000,34.100000,49.100000,371.000000,145.000000,14.500000,135.000000,130.000000,86.000000,100.000000,100.000000,1041.200000,1039.800000,9.000000,9.000000,39.800000,47.000000,371.000000

In [21]:
# Como df.info() no muestra todas las columnas ya que sobrepasa el límite de filas, 
# se utiliza pd.option_context para mostrar todas las columnas y sus tipos de datos.

with pd.option_context('display.max_rows', None):
    display(pd.DataFrame({'no_nulos': df.count(), 'dtype': df.dtypes}))

                  no_nulos    dtype
Unnamed: 0          145412    int64
Date                145412      str
Location            145412      str
MinTemp             143928  float64
MaxTemp             144159  float64
Rainfall            142152  float64
Evaporation          82658  float64
Sunshine             75616  float64
WindGustDir         135096      str
WindGustSpeed       135159  float64
WindDir9am          134850      str
WindDir3pm          141186      str
WindSpeed9am        143645  float64
WindSpeed3pm        142351  float64
Humidity9am         142759  float64
Humidity3pm         140907  float64
Pressure9am         130351  float64
Pressure3pm         130388  float64
Cloud9am             89542  float64
Cloud3pm             86076  float64
Temp9am             143646  float64
Temp3pm             141805  float64
RainToday           142152      str
RainTomorrow        142153      str
RainfallTomorrow    142153  float64

Notamos de este primer vistazo que las siguientes columnas tienen menos del 5% de faltantes:
- Unnamed (correspondiente al índice)
- Date
- Location
- MinTemp
- MaxTemp
- Rainfall
- WindDir3pm
- WindSpeed9am
- WindSpeed3pm
- Humidity9am
- Humidity3pm
- Temp9am
- Temp3pm
- RainToday
- RainTomorrow
- RainfallTomorrow

Las siguientes columnas tienen un faltante de aproximadamente 10%:
- WindGustDir
- WindGustSpeed
- WindDir9am
- Pressure9am
- Pressure3pm

Y por ultimo estas variables poseen una falta de hasta un 38%:
- Evaporation
- Sunshine
- Cloud9am
- Cloud3pm

### Limpieza

##### 1. Unnamed: 0

La primer columna, 'Unnamed: 0', representa el índice del dataset. Pero al examinarla detalladamente notamos que hay valores erroneos dentro de ella (no consecutivos, salteo, etc).
Existen 2 opciones: eliminarla y crearla nuevamente para que se respete el orden de las filas; o bien eliminarla definitivamente. SAeguiremos esta segunda opcion, ya que para el analisis posterior no será necesaria esta información.

In [25]:
df.drop(columns="Unnamed: 0", inplace=True)

df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,RainfallTomorrow
0,2008-12-01,Albury,13.6,22.5,0.6,NaN,NaN,W,45.0,W,...,23.8,1008.1,1007.2,8.0,NaN,16.8,20.8,No,No,0.0
1,2008-12-02,Albury,7.3,25.8,0.0,NaN,NaN,WNW,44.0,NNW,...,22.1,1011.1,1007.5,NaN,NaN,18.3,24.6,No,No,0.0
2,2008-12-03,Albury,13.2,26.2,0.0,NaN,NaN,WSW,46.0,W,...,31.5,1007.3,1009.4,NaN,2.0,21.2,23.4,No,No,0.0
3,2008-12-04,Albury,10.0,28.8,0.0,NaN,NaN,NE,23.0,SE,...,18.5,1017.6,1012.4,NaN,NaN,17.4,26.3,No,No,1.0
4,2008-12-05,Albury,17.4,32.4,1.0,NaN,NaN,W,41.0,ENE,...,34.6,1010.9,1005.9,7.0,8.0,17.9,29.1,No,No,0.2